# Generated by Django 5.0.4 on 2024-04-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blog_author_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
