# Generated by Django 5.0.4 on 2024-04-25 10:44

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_matchhighlight_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='matchhighlight',
            name='highlight',
            field=models.FileField(default=1, upload_to=user.models.highlight_file_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
