# Generated by Django 5.0.4 on 2024-04-25 10:52

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_match_location_alter_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
